### ISSUE TITLE
ngga upload bahasa pemrograman kesini mas?

### ISSUE THREAD

**Issue by tanwirulqulub999** [webprogrammingunpas/wpu-resolusi#63]
ngga upload bahasa pemrograman kesini mas?

**Comment by wtf666** [comment]
upload lah sekalian buat videonya

**Comment by acakdadu** [comment]
maksudnnya opo toh

**Comment by tanwirulqulub999** [comment]
wkwkwk maaf saya masih pemula pada github jadi kurang ngerti soal issues maupun pulls request masih bingung

**Comment by wtf666** [comment]
lgipula ni repo dah mati ga updet2

**Comment by ZenviL** [comment]
nggak kok masih ada yang nyoba,

**Comment by wtf666** [comment]
tpi ga dicommit wkoakwkwkkw liat aja update terakhir dah brp tahun

**Comment by yudibilly** [comment]
hadir

**Comment by tanwirulqulub999** [comment]
sebagai noob saya nyimak aja dah :(

**Comment by wtf666** [comment]
dh diem banyak notice yg penting malah hilang2 punyaku

**Comment by novasaputra11** [comment]
hadir

**Comment by hansputera** [comment]
Hadir

**Comment by hansputera** [comment]
Tutor java pak

**Comment by Andi-IM** [comment]
misi, java ato javascript?

**Comment by yudibilly** [comment]
> Tutor java pak

lihat channel kang pukis

**Comment by zumardirahman** [comment]
Oreo supremenya kang??

**Comment by Anangprasetya** [comment]
Hay semua apakabar

**Comment by samuelhutauruk2** [comment]
rame di mari.

**Comment by dedektegarapriyandi** [comment]
Aing Ketinggalan Gan

**Comment by bagasdwipaa** [comment]
hehew

**Comment by baredwan** [comment]
Saya malah baru tau nih

**Comment by hilmialmuhtadeb** [comment]
colek pak Dhika aja :D @sandhikagalih

**Comment by WahyutriNugroho** [comment]
sebagai nub di github saya nyimak

**Comment by evan-deusVult** [comment]
![NICE](https://user-images.githubusercontent.com/78480389/106840293-70689700-66d2-11eb-894c-dacfc5d83ae9.gif)

**Comment by aldisyah02** [comment]
Baru belajar github di pak sandhika 
telat 2 tahun owkowkwokw

**Comment by tyogautomo** [comment]
issue yang aneh

**Comment by Andi-IM** [comment]
Issue diisi komentar gabut

**Comment by wtf666** [comment]
manusia binatang semua wkwkwkwkkw pada kagak tau apa beneren gaptek sich
